/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PathFindingAlgorithm_NativeCall */

#ifndef _Included_PathFindingAlgorithm_NativeCall
#define _Included_PathFindingAlgorithm_NativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PathFindingAlgorithm_NativeCall
 * Method:    ffs
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_PathFindingAlgorithm_NativeCall_ffs
  (JNIEnv *, jobject, jint);

/*
 * Class:     PathFindingAlgorithm_NativeCall
 * Method:    clz
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_PathFindingAlgorithm_NativeCall_clz
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
